export default [
  {
    id: 1,
    label: 'How do you spell Linda’s real name?',
    answer: 'Yu Hsuan Huang',
    open: false,
  },
  {
    id: 2,
    label: 'Is Linda an early bird or night owl?',
    answer: 'Night Owl',
    open: false,
  },
  {
    id: 3,
    label: 'What is Linda’s favorite color?',
    answer: 'Purple',
    open: false,
  },
  {
    id: 4,
    label: 'How did Linda come to faith?',
    answer: '',
    open: false,
  },
  {
    id: 5,
    label: 'Which LOTR character is Linda?',
    answer: '',
    open: false,
  },
  {
    id: 6,
    label: 'How long did Linda used to ride her mopad in order to reach her church in Taiwan?',
    answer: 'Roughtly 45 minutes',
    open: false,
  },
  {
    id: 7,
    label: 'What did Linda major in?',
    answer: 'Fashion Marketing',
    open: false,
  },
  {
    id: 8,
    label: 'How dilated was Linda when she arrived at the hospital?',
    answer: '9cm',
    open: false,
  },
  {
    id: 9,
    label: 'What is something you appreciate about Linda?',
    answer: '',
    open: false,
  },
  {
    id: 10,
    label: 'How many siblings does Linda have?',
    answer: '2',
    open: false,
  },
  {
    id: 11,
    label: 'Which sport team does Linda support?',
    answer: 'None / the one with the better-looking uniform / the one with the friendlier-/happier-looking coach',
    open: false,
  },
  {
    id: 12,
    label: 'What high school club(s) was Linda a president of?',
    answer: 'Guitar club, student government',
    open: false,
  },
  {
    id: 13,
    label: 'Why did Linda cross the road?',
    answer: '',
    open: false,
  },
  {
    id: 14,
    label: 'How old is Linda today?',
    answer: '29',
    open: false,
  },
  {
    id: 15,
    label: 'How has Linda helped you love Christ more in the past year?',
    answer: '',
    open: false,
  },
  {
    id: 16,
    label: 'Did Linda graduate university late?',
    answer: 'Yes, because she went to Sweden for an exchange semester',
    open: false,
  },
  {
    id: 17,
    label: 'How many ECCD staff members’ homes did Linda live in before getting married? Please list them. Bonus for the correct order.',
    answer: '3: Woodwards, Lims, Welkners',
    open: false,
  },
  {
    id: 18,
    label: 'Linda calls you at 3am. What does she want to talk about?',
    answer: '',
    open: false,
  },
  {
    id: 19,
    label: 'What are some of Linda’s pet peeves?',
    answer: 'Not using coasters, dirty nails, etc.',
    open: false,
  },
  {
    id: 20,
    label: 'What did Linda used to do before becoming a full-time, lovely, gentle, caring wife and mother? ',
    answer: 'Barista, sales at GAP, fashion market middleman',
    open: false,
  },
  {
    id: 21,
    label: 'What piece of encouragement would you give Linda today?',
    answer: '',
    open: false,
  },
  {
    id: 22,
    label: 'How many Lindas does it take to change a light bulb?',
    answer: '',
    open: false,
  },
  {
    id: 23,
    label: 'How many 10km runs has Linda completed in her life?',
    answer: '0',
    open: false,
  },
  {
    id: 24,
    label: 'Is Linda right-handed or left-handed?',
    answer: 'Right',
    open: false,
  },
  {
    id: 25,
    label: '“Listen, Linda. Linda, Linda, listen to me, ___________________________”',
    answer: '',
    open: false,
  },
  {
    id: 26,
    label: 'What is Linda’s favorite hotel in the UAE?',
    answer: 'The Chedi Al Bait',
    open: false,
  },
  {
    id: 27,
    label: 'What’s one of Linda’s special talents?',
    answer: 'She can remember lyrics of hundreds of Taiwanese songs',
    open: false,
  },
  {
    id: 28,
    label: 'Hi',
    answer: '',
    open: false,
  },
  {
    id: 29,
    label: 'Hi',
    answer: '',
    open: false,
  },
  {
    id: 30,
    label: 'Hi',
    answer: '',
    open: false,
  },
];
